// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHgI7OEyUWSBQZELbfsZ8PbvgbvlSrPA',
    appId: '1:61504805152:web:5de98af649166cc6861f45',
    messagingSenderId: '61504805152',
    projectId: 'sagewest-67be1',
    authDomain: 'sagewest-67be1.firebaseapp.com',
    storageBucket: 'sagewest-67be1.firebasestorage.app',
    measurementId: 'G-KVSCBSEKE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv8pWW3ceJ4ihPL_1wZyvF_tZsKZIUCEY',
    appId: '1:61504805152:android:5d551a4076113f57861f45',
    messagingSenderId: '61504805152',
    projectId: 'sagewest-67be1',
    storageBucket: 'sagewest-67be1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX3Uns-V74ZdFD1g-m_2vB_7RjBcf9I8U',
    appId: '1:61504805152:ios:c2029060f39a6431861f45',
    messagingSenderId: '61504805152',
    projectId: 'sagewest-67be1',
    storageBucket: 'sagewest-67be1.firebasestorage.app',
    iosBundleId: 'com.example.borsatakip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX3Uns-V74ZdFD1g-m_2vB_7RjBcf9I8U',
    appId: '1:61504805152:ios:c2029060f39a6431861f45',
    messagingSenderId: '61504805152',
    projectId: 'sagewest-67be1',
    storageBucket: 'sagewest-67be1.firebasestorage.app',
    iosBundleId: 'com.example.borsatakip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtHgI7OEyUWSBQZELbfsZ8PbvgbvlSrPA',
    appId: '1:61504805152:web:2a09b06e167a4b6d861f45',
    messagingSenderId: '61504805152',
    projectId: 'sagewest-67be1',
    authDomain: 'sagewest-67be1.firebaseapp.com',
    storageBucket: 'sagewest-67be1.firebasestorage.app',
    measurementId: 'G-3DB3Q1V99C',
  );
}
